### PR TITLE
Fix on FreeBSD

### PR DESCRIPTION
**Pull request by myfreeweb**

### CODE REVIEW

**Comment by eminence** [comment]
Thanks for the fix.  I don't have easy access to a FreeBSD machine with rust, but this looks good to me.  It's surprising to me that `TIOCGWINSZ` is a c_ulong and not a c_int, but 🤷‍♂

**Comment by Freaky** [comment]
@eminence Any chance of publishing a new release for this?

**Comment by eminence** [comment]
Absolutely, thank you for the reminder about this.  I've published this fix as v0.1.11

**Comment by Freaky** [comment]
Thanks :)

**Pull request merged**
