### PR TITLE
Fixed terminal_size for OSX. Fixed test call of stty on OSX.

### LINKED ISSUE #5: Mac not working
Hey,

unfortunately mac is not working, just wanted to let you know. Maybe if I have to time I will look into that since I need the terminal size :(

Best,
Sebastian

### PR DESCRIPTION
**Pull request by flxo**
TIOCGWINSZ is 0x00005413 for OSX.
Furthermore `stty` takes different arguments on OSX than on Linux.

This should fix #5.

### CODE REVIEW

**Comment by flxo** [comment]
Hi @eminence,

any change to get this merged?

Thanks, @flxo

**Comment by eminence** [comment]
Wow, I forgot about this for half a year!  Sorry about that, yes I'll merge this tonight

**Comment by flxo** [comment]
Thanks! Would be great if you could (in the case you merge the commit) update the crate on crates.io. I'd like to publish one there and cannot with git deps. See [here](https://github.com/flxo/rogcat/issues/2).

**Comment by flxo** [comment]
Thanks. I switched to `term_size` because I had some time yesterday and wanted to get forward. Anyway - thanks again.

**Pull request merged**
