### PR TITLE
Update rustix to 0.36.3

### PR DESCRIPTION
**Pull request by messense**
Closes #47

### CODE REVIEW

**Comment by eminence** [comment]
Thank you for the OSX fix!

**Comment by messense** [comment]
A new release to crates.io would be nice, thanks in advance!

**Comment by pinkforest** [comment]
Yeah would be nice :) there was just some wasm32 stuff fixed elsewhere and we're seeing rustix doubling up in dependency tree. Thanks :heart:

**Comment by eminence** [comment]
`v0.2.3` is now published with this change

**Pull request merged**
